### ISSUE TITLE
请问这个项目已经完成了吗？

### ISSUE THREAD

**Issue by ysj1173886760** [jackwener/Readings-in-Database-Systems-5th-CN#18]
Hello，如果项目还是在进行中的我很希望可以帮忙一起翻译，也相当于是督促自己读完这本书了:)。

**Comment by jackwener** [comment]
@ysj1173886760 还没有，现在忙于开发工作，进度好久没动了，可以一起翻译！😀🚀

**Comment by jackwener** [comment]
你可以用邮件(github主页栏就有)联系下我（毕竟issue里所有的内容都是有记录留存的，就不放联系方式了哈哈哈

**Comment by ysj1173886760** [comment]
cool :)
